# Generated by Django 3.1.3 on 2020-11-21 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0004_mypoll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.AddField(
            model_name='mypoll',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
