# Generated by Django 3.1.3 on 2020-11-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_mypoll_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypoll',
            name='author',
        ),
    ]
